### ISSUE TITLE
Image no show in NPM Page

### ISSUE THREAD

**Issue by TiagoDanin** [TiagoDanin/Gen-README#64]
Change relative url to absolute url

**Comment by Troy96** [comment]
Hi @TiagoDanin,

I want to take this up for Hacktoberfest. Can I work on this?

**Comment by TiagoDanin** [comment]
> Hi @TiagoDanin,
> 
> I want to take this up for Hacktoberfest. Can I work on this?

Yep :)

**Comment by Troy96** [comment]
Great, thanks :)

**Comment by Troy96** [comment]
hey @TiagoDanin can you please explain the issue in more detail?

**Comment by TiagoDanin** [comment]
![image](https://user-images.githubusercontent.com/5731176/96648330-8d38b480-1305-11eb-9872-2221c40f46bf.png)
This has been fixed in NPM, now accept relative path from Github.

**Comment by Troy96** [comment]
Ok cool
